services:
    accounts:
        image: "iannunes/accounts:latest"
        container_name: accounts
        ports:
            - "8080:8080"
        deploy:
          resources:
            limits:
              memory: "700m"
        networks:
          - naibank
    loans:
      image: "iannunes/loans:latest"
      container_name: loans
      ports:
        - "8090:8090"
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - naibank
    cards:
      image: "iannunes/cards:latest"
      container_name: cards
      ports:
        - "9000:9000"
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - naibank
networks:
  naibank:
      driver: "bridge"