build:
  version: "1.0"

loans:
  message: "Welcome to NaiBank loans related prod APIs "
  contactDetails:
    name: "Pelias Sudhir - Product Owner"
    email: "pelias@naibank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956